# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-04 16:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('login', models.CharField(max_length=50, verbose_name='Login Name')),
                ('image', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('user_id', models.IntegerField(unique=True, verbose_name='Gitid')),
                ('followers_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('site_admin', models.BooleanField(verbose_name='Siteadmin')),
                ('repos_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gituser_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gituser_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
