# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-05 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gituser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gituser',
            name='updated_by',
        ),
    ]
